name: Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    if: contains(github.event.commits.*.message, '[build]') == true

    name: Build Poker and draft Release
    runs-on: ubuntu-latest

    steps:
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '16'

    - name: Copy Repo Files
      uses: actions/checkout@v2

    - name: Install Modules
      run: yarn

    - name: Lint
      run: yarn lint-strict

    - name: TSC
      run: yarn tsc --noEmit

    - name: Build Poker
      env:
        NODE_ENV: production
      run: yarn build

    - name: Create poker.zip
      run: |
        mv build poker
        zip -r poker.zip ./poker

    - name: get-npm-version
      id: package-version
      uses: martinbeentjes/npm-get-version-action@main

    - name: Create semver tag
      uses: EndBug/latest-tag@latest
      with:
        ref: v${{ steps.package-version.outputs.current-version}}

    - name: Draft Release
      uses: softprops/action-gh-release@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag_name: v${{ steps.package-version.outputs.current-version}}
        draft: true
        name: v${{ steps.package-version.outputs.current-version}}
        body: |
          作者目前还没有提交到 Chrome Store 上，所以目前的发布还并不是 crx 文件，而是 zip 文件，安装方式有点差异：

          1. 先打开 Chrome，在地址栏输入 chrome://extensions 后进入扩展程序管理页面
          2. 启用页面右上角的「开发者模式」
          3. 然后解压 poker.zip ，将解压出来的文件夹拖拽到这个页面上，即可完成安装

          最新开发版可以体验到最新开发的功能，**但程序可能会有严重的缺陷，以至于无法正常使用的情况**，请酌情考虑。
          建议使用稳定版作为日常使用，⬇️往下翻看。
        files: |
          LICENSE
          poker.zip
