name: Pull Request Code Check

on:
  pull_request:
    branches:
      - master
      - dev

jobs:
  Check:
    name: ESLint & TSC
    runs-on: ubuntu-latest

    steps:
      - name: Copy Repo Files
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Modules
        run: yarn

      - name: ESLint
        run: yarn lint-strict

      - name: TSC
        run: yarn tsc --noEmit
