name: Pull Request Code Check

on:
  pull_request:
    branches:
      - master

jobs:
  ESlint:
    name: ESlint
    runs-on: ubuntu-latest

    steps:
    - name: Copy Repo Files
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '16'

    - name: ESLint
      run: |
        yarn
        yarn lint-strict

  tsc:
    name: TSC
    runs-on: ubuntu-latest

    steps:
    - name: Copy Repo Files
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '16'

    - name: yarn tsc --noEmit
      run: |
        yarn
        yarn tsc --noEmit
