name: 'Latest Release'

on:
  push:
    branches:
      - dev

jobs:
  latest-release:
    name: Latest Release
    runs-on: ubuntu-latest

    steps:
      - name: Copy Repo Files
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16'

      - name: Install Modules
        run: yarn

      - name: ESLint
        run: yarn lint-strict

      - name: TSC
        run: yarn tsc --noEmit

      - name: Build Poker
        env:
          NODE_ENV: production
        run: yarn build

      - name: Create poker.zip
        run: |
          mv build poker
          zip -r poker.zip ./poker
          
      - name: Latest Release
        uses: softprops/action-gh-release@v1
        if: startsWith(latest, 'refs/tags/')
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true
          tag_name: latest
          name: 最新开发版(latest development release)
          body: |
            此为开发版，并不是 crx 文件，而是 zip 文件，安装方式有点差异：

            先打开 Chrome，在地址栏输入 chrome://extensions 后进入扩展程序管理页面启用页面右上角的「开发者模式」然后解压 poker.zip ，将解压出来的文件夹拖拽到这个页面上，即可完成安装
          files: |
            LICENSE
            poker.zip

      # - uses: "marvinpinto/action-automatic-releases@latest"
      #   with:
      #     repo_token: "${{ secrets.GITHUB_TOKEN }}"
      #     automatic_release_tag: "latest"
      #     title: 最新开发版(latest development release)
      #     prerelease: true
      #     files: |
      #       LICENSE.txt
      #       poker.zip
